# Site settings
title: Quarter-Life Coder
header-img: img/home-bg.png
email: marianharper117@gmail.com
copyright_name: marianharper
description: > # this means to ignore newlines until "baseurl:"
  My coding journey, and how it helped me through my crisis.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: marian_harper
github_username:  marianharper
learn_profile: marianharper
email_username: marianharper117@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
